spring:
  config:
    import: db/mysql-dev.yml
eureka:
  client:
    register-with-eureka: true  # 是否向注册中心注册自己
    fetchRegistry: true   # 是否从注册中心抓取已有的注册信息，默认true，集群必须设置为true
    service-url:
      # 集群中各个服务注册中心的地址，实际上先一个节点即可，因为服务器集群会复制提供者信息。
      defaultZone: ${docker.life.EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    instance-id: cj-life-middle-apc/${server.port}	 # 服务实例Id
    prefer-ip-address: true
    #调用者feign只认spring.application.name，不认此处配置应用名
    #所以不论服务提供者还是feign消费者，spring.application.name和eureka.instance.appname都配置就最好了
    #feign调用方大小写不区分，而注册中心永远显示为大写
    #eureka.instance.appname的配置名在注册中心会覆盖spring.application.name而显示，但feign认只spring.application.name
    appname: cj-life-middle-apc
    #注册中心点状态跳转到swagger
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}${server.servlet.context-path}doc.html
life:
  test:
    feign:
      #如果feign调用的服务在docker内。注册中心会返回服务的容器内ip地址导致连接失败。因此需要适配
      #适配原理：通过spring的环境切换，在dev环境下配置适配器，在prod环境下没有此适配配置
      #因此在声明feign时需要：@FeignClient(name = "cj-life-middle-uc",url = "${life.test.feign.adapter.docker.uc.url:}")
      #意为：如果属性life.test.feign.adapter.docker.uc.url为空则无。因为在prod环境下没有配置该属性，因此为空。为空则会启动容器内ip调用。
      adapter:
        docker:
          uc:
            url: localhost:30000