spring:
  config:
    import: db/mysql-prod.yml
eureka:
  client:
    register-with-eureka: true  # 是否向注册中心注册自己
    fetchRegistry: true   # 是否从注册中心抓取已有的注册信息，默认true，集群必须设置为true
    service-url:
      # 集群中各个服务注册中心的地址，实际上先一个节点即可，因为服务器集群会复制提供者信息。
      defaultZone: ${docker.life.EUREKA_SERVER_URL:http://eureka8761:8761/eureka}
  instance:
    instance-id: cj-life-middle-apc/${server.port}	 # 服务实例Id
    prefer-ip-address: true
    appname: cj-life-middle-apc
    status-page-url: http://localhost:${server.port}${server.servlet.context-path}doc.html